import fs from "fs";
import path from "path";
import { execFile, spawn } from "child_process";
import { isPortOpen } from "./detect";

export const COMPOSE_FILE = "docker-compose.queueway.yml";

export type ServiceName = "postgres" | "redis" | "rabbitmq";

export interface ServiceSpec {
  name: ServiceName;
  /** Host port. Chosen by the wizard, never hardcoded — see findFreePort. */
  port: number;
  /** Extra host port (RabbitMQ's management UI). */
  extraPort?: number;
  user?: string;
  password?: string;
  database?: string;
}

/** Runs a command, streaming its output so a long `docker pull` isn't a silent freeze. */
export function runStreaming(cmd: string, args: string[]): Promise<boolean> {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { stdio: "inherit", windowsHide: true, shell: false });
    child.on("error", () => resolve(false));
    child.on("close", (code) => resolve(code === 0));
  });
}

function serviceBlock(spec: ServiceSpec, slug: string): string {
  const container = `queueway-${slug}-${spec.name}`;

  if (spec.name === "postgres") {
    return `  postgres:
    image: postgres:16-alpine
    container_name: ${container}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${spec.database}
      POSTGRES_USER: ${spec.user}
      POSTGRES_PASSWORD: ${spec.password}
    ports:
      - "${spec.port}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${spec.user} -d ${spec.database}"]
      interval: 5s
      timeout: 5s
      retries: 10
`;
  }

  if (spec.name === "redis") {
    return `  redis:
    image: redis:7-alpine
    container_name: ${container}
    restart: unless-stopped
    # appendonly keeps queued jobs on disk, so a Redis restart doesn't drop them.
    command: redis-server --appendonly yes
    ports:
      - "${spec.port}:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
`;
  }

  return `  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: ${container}
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${spec.user}
      RABBITMQ_DEFAULT_PASS: ${spec.password}
    ports:
      - "${spec.port}:5672"
      - "${spec.extraPort}:15672"
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
`;
}

/**
 * Pulls the service blocks out of an already-generated compose file so that
 * adding a second service doesn't silently delete the first. Without this,
 * setting up Redis after PostgreSQL rewrites the file with Redis alone and
 * Docker reports the PostgreSQL container as an orphan.
 */
function existingBlocks(file: string): Record<string, string> {
  if (!fs.existsSync(file)) return {};
  const content = fs.readFileSync(file, "utf8");
  const servicesAt = content.indexOf("\nservices:\n");
  const volumesAt = content.indexOf("\nvolumes:\n");
  if (servicesAt === -1) return {};

  const body = content.slice(
    servicesAt + "\nservices:\n".length,
    volumesAt === -1 ? undefined : volumesAt,
  );

  const blocks: Record<string, string> = {};
  // Top-level service keys are indented exactly two spaces.
  const parts = body.split(/^ {2}(?=[a-z])/m).filter((p) => p.trim());
  for (const part of parts) {
    const name = part.slice(0, part.indexOf(":")).trim();
    if (name) blocks[name] = `  ${part.replace(/\s+$/, "")}\n`;
  }
  return blocks;
}

export function writeComposeFile(specs: ServiceSpec[], slug: string): string {
  const file = path.resolve(process.cwd(), COMPOSE_FILE);

  // Start from whatever is already configured, then overwrite only the
  // services being set up right now.
  const blocks = existingBlocks(file);
  for (const spec of specs) blocks[spec.name] = serviceBlock(spec, slug);

  const volumeFor: Record<string, string> = {
    postgres: "  pgdata:",
    redis: "  redisdata:",
    rabbitmq: "  rabbitdata:",
  };
  const volumes = Object.keys(blocks)
    .map((name) => volumeFor[name])
    .filter(Boolean);

  const content = `# Generated by \`queueway init\` — safe to commit and to edit.
# Runs Queueway's own services; nothing else on this machine is touched.
#
#   docker compose -f ${COMPOSE_FILE} up -d      start
#   docker compose -f ${COMPOSE_FILE} ps         status
#   docker compose -f ${COMPOSE_FILE} down       stop (data kept)
#   docker compose -f ${COMPOSE_FILE} down -v    stop and delete all job data

name: queueway-${slug}

services:
${Object.values(blocks).join("\n")}
volumes:
${volumes.join("\n")}
`;

  fs.writeFileSync(file, content, "utf8");
  return file;
}

/**
 * Waits until the service is actually accepting connections. Compose returning
 * success only means the container was created — Postgres in particular takes
 * several more seconds to finish initialising on first run.
 */
export async function waitForPort(port: number, timeoutMs = 90_000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await isPortOpen(port)) return true;
    await new Promise((r) => setTimeout(r, 1000));
  }
  return false;
}

/** Images each service needs, pulled up front so failures are legible. */
const IMAGES: Record<ServiceName, string> = {
  postgres: "postgres:16-alpine",
  redis: "redis:7-alpine",
  rabbitmq: "rabbitmq:3.13-management",
};

/**
 * Pulls the image before starting anything. Doing this as its own step means a
 * slow download shows real progress, and a transient engine error (Docker
 * Desktop answers before its image store is ready) can simply be retried
 * instead of taking the whole setup down with it.
 */
export async function pullImage(service: ServiceName, attempts = 3): Promise<boolean> {
  const image = IMAGES[service];
  for (let attempt = 1; attempt <= attempts; attempt++) {
    if (await runStreaming("docker", ["pull", image])) return true;
    if (attempt < attempts) {
      console.log(`\n   ⏳ Docker wasn't ready — retrying in 10s (${attempt}/${attempts - 1})…\n`);
      await new Promise((r) => setTimeout(r, 10_000));
    }
  }
  return false;
}

export async function composeUp(attempts = 2): Promise<boolean> {
  for (let attempt = 1; attempt <= attempts; attempt++) {
    if (await runStreaming("docker", ["compose", "-f", COMPOSE_FILE, "up", "-d"])) return true;
    if (attempt < attempts) {
      console.log(`\n   ⏳ Retrying in 10s…\n`);
      await new Promise((r) => setTimeout(r, 10_000));
    }
  }
  return false;
}

/** Does a Docker volume from a previous setup still exist? */
export async function volumeExists(slug: string, service: ServiceName): Promise<boolean> {
  const suffix: Record<ServiceName, string> = {
    postgres: "pgdata",
    redis: "redisdata",
    rabbitmq: "rabbitdata",
  };
  const name = `queueway-${slug}_${suffix[service]}`;
  return new Promise((resolve) => {
    execFile(
      "docker",
      ["volume", "ls", "-q", "--filter", `name=^${name}$`],
      { timeout: 10_000, windowsHide: true },
      (err, stdout) => resolve(!err && String(stdout).trim().length > 0),
    );
  });
}

/** Stops the generated stack and deletes its volumes — used to reset stale data. */
export async function composeDownVolumes(): Promise<boolean> {
  return runStreaming("docker", ["compose", "-f", COMPOSE_FILE, "down", "-v"]);
}

/**
 * Deletes one service's data volume, leaving the others alone.
 *
 * `docker compose down -v` removes every volume in the file, so resetting
 * PostgreSQL would also throw away whatever Redis still had queued. Resetting
 * one service must not destroy another's data.
 */
export async function removeVolume(slug: string, service: ServiceName): Promise<boolean> {
  const suffix: Record<ServiceName, string> = {
    postgres: "pgdata",
    redis: "redisdata",
    rabbitmq: "rabbitdata",
  };
  const container = `queueway-${slug}-${service}`;
  const volume = `queueway-${slug}_${suffix[service]}`;

  // The container has to let go of the volume before it can be removed.
  await new Promise<void>((resolve) =>
    execFile("docker", ["rm", "-f", container], { timeout: 30_000, windowsHide: true }, () =>
      resolve(),
    ),
  );

  return new Promise((resolve) => {
    execFile("docker", ["volume", "rm", volume], { timeout: 30_000, windowsHide: true }, (err) =>
      resolve(!err),
    );
  });
}

/** Is the container this project generated actually running right now? */
export async function containerRunning(slug: string, service: ServiceName): Promise<boolean> {
  const name = `queueway-${slug}-${service}`;
  return new Promise((resolve) => {
    execFile(
      "docker",
      ["ps", "--filter", `name=^${name}$`, "--filter", "status=running", "--format", "{{.Names}}"],
      { timeout: 10_000, windowsHide: true },
      (err, stdout) => resolve(!err && String(stdout).trim().length > 0),
    );
  });
}
